name: CMake with Clang 15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM/Clang 15
      run: |
        sudo apt update
        sudo apt install -y clang-15 llvm-15-dev libclang-15-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-15 100

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake with LLVM/Clang 15
      working-directory: build
      run: |
        cmake .. \
          -DLLVM_DIR=/usr/lib/llvm-15/lib/cmake/llvm \
          -DClang_DIR=/usr/lib/llvm-15/lib/cmake/clang \
          -DCMAKE_C_COMPILER=clang-15 \
          -DCMAKE_CXX_COMPILER=clang++-15 \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: build
      run: make

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
